FROM opensearchproject/opensearch:2.0.1
RUN /usr/share/opensearch/bin/opensearch-plugin install https://artifacts.opensearch.org/releases/plugins/analysis-kuromoji/2.0.1/analysis-kuromoji-2.0.1.zip
RUN /usr/share/opensearch/bin/opensearch-plugin install https://artifacts.opensearch.org/releases/plugins/analysis-icu/2.0.1/analysis-icu-2.0.1.zip
